# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/829ae7c7-a0fa-40d9-b86f-85faf3cfb6fb";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/55AD-D24B";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

   fileSystems."/mnt/NAS" = {
     device = "//192.168.20.41/NAS";  # Replace with your NAS IP and share name
     fsType = "cifs";
     options = [
       "credentials=/etc/nixos/secrets/smb-credentials"
       "uid=1000"        # Your user ID (run `id` to check)
       "gid=100"         # Your group ID (usually 'users' group)
       "iocharset=utf8"
       "file_mode=0777"
       "dir_mode=0777"
       "vers=3.0"        # SMB version, try 2.1 or 1.0 if 3.0 doesn't work
       "nofail"          # Don't fail boot if mount fails
       "x-systemd.automount"  # Auto-mount on access
       "x-systemd.device-timeout=10"
     ];
   };

   fileSystems."/mnt/Backups" = {
     device = "//192.168.20.41/Backups";  # Replace with your NAS IP and share name
     fsType = "cifs";
     options = [
       "credentials=/etc/nixos/secrets/smb-credentials"
       "uid=1000"        # Your user ID (run `id` to check)
       "gid=100"         # Your group ID (usually 'users' group)
       "iocharset=utf8"
       "file_mode=0777"
       "dir_mode=0777"
       "vers=3.0"        # SMB version, try 2.1 or 1.0 if 3.0 doesn't work
       "nofail"          # Don't fail boot if mount fails
       "x-systemd.automount"  # Auto-mount on access
       "x-systemd.device-timeout=10"
     ];
   };

   fileSystems."/mnt/SSD4TB" = {
     device = "/dev/sda";
     fsType = "ext4";  # Replace with your actual filesystem (ext4, ntfs, xfs, etc.)
     options = [
       "defaults"
       "nofail"          # Don't fail boot if disk isn't present
       "user"            # Allow regular users to mount/unmount
       "exec"            # Allow execution of binaries
     ];
   };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/2289fdd2-be17-4078-928c-68e8601f3799"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
